//Auth action type
export const AUTH_SIGNUP_PENDING = "AUTH_SIGNUP_PENDING"
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS"
export const AUTH_SIGNUP_REJECT = "AUTH_SIGNUP_REJECT"
export const AUTH_SIGNIN_PENDING = "AUTH_SIGNIN_PENDING"
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS"
export const AUTH_SIGNIN_REJECT = "AUTH_SIGNIN_REJECT"
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
export const AUTH_FIRST_LOGIN = "AUTH_FIRST_LOGIN"
export const AUTH_MESSAGE_CLEAR = "AUTH_MESSAGE_CLEAR"
export const AUTH_SAVE_USER = "AUTH_SAVE_USER"

//Card action type
export const CART_ADD_PENDING = "CART_ADD_PENDING"
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS"
export const CART_ADD_REJECT= "CART_ADD_REJECT"
export const CART_SAVE_NEW = "CART_SAVE_NEW"
export const CART_ADD_MESSAGE = "CART_ADD_MESSAGE"
export const CART_CLEAR_ALL = "CART_CLEAR_ALL"
export const CART_MESSAGE_CLEAR = "CART_MESSAGE_CLEAR"


//Order action type
export const ORDER_ADD_LIST = "ORDER_ADD_LIST"
export const ORDER_ADD_MESSAGE = "ORDER_ADD_MESSAGE"
export const ORDER_MESSAGE_CLEAR = "ORDER_MESSAGE_CLEAR"
export const ORDER_UPDATE_ITEM = "ORDER_UPDATE_ITEM"